name = "oracle-universe-api"
main = "worker.ts"
compatibility_date = "2025-06-01"
account_id = "a5eabdc2b11aae9bd5af46bd6a88179e"
workers_dev = true

# POCKETBASE_URL is set as a wrangler secret (private)
